{{- $namespace := .Values.namespace.name -}}
{{- range .Values.environment }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace  }}-{{ . }}
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace  }}